In [1]:
import numpy as np

### Question 1

Write a Python/NumPy code block that finds the distinct/unique common items between these two arrays:


a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])


b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])



Your output should contain only the distinct overlapping values. For example, if a 2 is found in both array a and array b,
your output should contain only one 2 even if array a contains more than one 2 within it.

In [2]:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6]) # A array 
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8]) # B Array

# Solution is using intersect1 dimentional function which intersects between the two arrays of 1 dimention
intersect_values = np.intersect1d(a,b)
print("Intersect values are : ", intersect_values)

Intersect values are :  [2 4]


### Question 2

2. Create the following 5x3 array using knowledge you have of Python’s / NumPy’s sequencing functionality so that you
do not need to explicitly key in every integer value.

1 6 11

2 7 12

3 8 13

4 9 14

5 10 15

In [3]:
array = np.arange(1,16) # A range of arrays from 1 to 15 (16 is exclusive)
array = np.reshape(array, (5,3)) # Reshaping the array to 5 x3 dimention 
array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

### Question 3

You are given the following two arrays:

a = np.array([12, 5, 7, 15, 3, 1, 8])

b = np.array([14, 6, 3, 11, 19, 12, 5])

Write a Python/Numpy code block that removes from array a any items that are also present in array b.



In [4]:
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])
# Solution using Numpy set difference between 1 D arrays function 

array = np.setdiff1d(a , b)
print("Removing elements of B from A is :", array)

Removing elements of B from A is : [ 1  7  8 15]


#### Question 4

Suppose you have ridden a bicycle from New York City to Key West, Florida. Your bicycle odometer shows the total
miles you have travelled thus far, which you make a note of each day with paper and pencil. Your first two entries might
be ‘55’ and ‘120’, indicating that you rode your bike 55 miles on day 1 and 65 miles on day 2. Your task is to create a
NumPy array wherein you can record the cumulative miles you recorded each day during your trip. Then use your
Python skills to show the total miles that you rode each day. Assume the trip took a total of 35 days and included at
least 4 non-consecutive days where no cycling was possible due to either weather conditions or personal
fatigue/soreness. For the remaining 31 days, you would have covered the entire distance between NYC and Key West.
Complete your work within your Jupyter Notebook for this assignment and be sure to include a writeup explaining your
approach to this problem, including the ways in which you decided to make use of NumPy.

In [5]:
ridden_bicycle_miles = np.array([55,65]) # keep adding additional miles as per days , for holidy add zero

#####  We need 33 more day based  miles  covered (where 4 days covered miles would be 0 as those days would be off)
* so we use random function to get the integers based mile values and later onward we add a % 35 % 4 condition to add 0 (as off day there)



In [6]:
# Adding Randomly the elements or miles ridden 
random_miles = np.random.randint(30,65, size = 33) # 33 elements

# Ridden bicycle miles are being created by appending the random miles at the end of the numpy list 
ridden_bicycle_miles = np.append(ridden_bicycle_miles , random_miles)


In [15]:
# Looping through all the elements and speifing zero where the day is termed as off
for index, array_value in enumerate(ridden_bicycle_miles):
    if index+1  % (35//4) == 0:
        print("Yes")
        # The reason to do 35/4 is because we will have 4 days off
        ridden_bicycle_miles[index] = 0 # replacing the value with zero

In [16]:
ridden_bicycle_miles

array([ 0, 65, 50, 42, 40, 34, 38, 62,  0, 56, 63, 52, 52, 58, 33, 35,  0,
       49, 49, 37, 51, 51, 30, 43,  0, 40, 37, 39, 47, 49, 62, 34,  0, 46,
       48])

In [17]:
# For this solution, it requires cummulative frequency distribution
cummulative_frequencies = np.cumsum(ridden_bicycle_miles)
print("Trip cumulative miles list are :", cummulative_frequencies)

Trip cumulative miles list are : [   0   65  115  157  197  231  269  331  331  387  450  502  554  612
  645  680  680  729  778  815  866  917  947  990  990 1030 1067 1106
 1153 1202 1264 1298 1298 1344 1392]


### Question 5

Open the Jupyter Notebook provided to you with this assignment. The first code block within that file will load a
small data set from a GitHub repository into a NumPy 2D array. The original source of that data contains an overview of
its contents:
https://data.cityofnewyork.us/Environment/Water-Consumption-In-The-New-York-City/ia2d-e54m
Scroll down to the bottom of that page to access an interactive data viewer that includes the column headings for the
data.
Using the NumPy array that has been loaded for you in the Jupyter Notebook, answer the following questions using
NumPy’s slicing, methods, and functions:


 What is the maximum yearly NYC consumption of water in millions of gallons per day?


 How many calendar years are represented within this data set? NumPy's shape command is one way to find
out.


 What is the mean and the standard deviation of the per capita daily water consumption?


 What is the increase or decrease in population from year to year? Use NumPy's `diff` function to create an array
of differences and save that to a variable called "pop_diff", then print that variable to the screen.

In [10]:
import pandas

# supress scientific notation
np.set_printoptions(suppress = True)

# read the data file from GitHub and convert to a NumPy ndarray object
nyc_water = pandas.read_csv('https://raw.githubusercontent.com/jtopor/DAV-5400/master/Week4/Water_Consumption_In_The_New_York_City.csv').as_matrix()

# verify you have an ndarray object
type(nyc_water)

c:\users\m shafay amjad\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:7: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  import sys


numpy.ndarray

In [16]:
nyc_water

array([[   1979. , 7102100. ,    1512. ,     213. ],
       [   1980. , 7071639. ,    1506. ,     213. ],
       [   1981. , 7089241. ,    1309. ,     185. ],
       [   1982. , 7109105. ,    1382. ,     194. ],
       [   1983. , 7181224. ,    1424. ,     198. ],
       [   1984. , 7234514. ,    1465. ,     203. ],
       [   1985. , 7274054. ,    1326. ,     182. ],
       [   1986. , 7319246. ,    1351. ,     185. ],
       [   1987. , 7342476. ,    1447. ,     197. ],
       [   1988. , 7353719. ,    1484. ,     202. ],
       [   1989. , 7344175. ,    1402. ,     191. ],
       [   1990. , 7335650. ,    1424. ,     194. ],
       [   1991. , 7374501. ,    1469. ,     199. ],
       [   1992. , 7428944. ,    1369. ,     184. ],
       [   1993. , 7506166. ,    1368.5,     182. ],
       [   1994. , 7570458. ,    1357.7,     179. ],
       [   1995. , 7633040. ,    1325.7,     174. ],
       [   1996. , 7697812. ,    1297.9,     169. ],
       [   1997. , 7773443. ,    1205.5,     1

##### part 1 
Requries slicing to get the numpy array of gallons
Then reshaping to a single Dimention instead of 2D
Then finding the maximum


In [13]:
max_yearly_nyc_consumption_water_in_millions = max(nyc_water[:,2].reshape(1,-1)[0]) # Slicing and converting to a one Dimention array

In [14]:
print("Maximum yearly NYC consumption of water in millions of gallons per day is ", max_yearly_nyc_consumption_water_in_millions)

Maximum yearly NYC consumption of water in millions of gallons per day is  1512.0


#### part 2
How many calendar years are represented within this data set? NumPy's shape command is one way to find
out.

* Sol: using the shape commands in Numpy

In [15]:
calendar_years  = nyc_water.shape[0]
print("Calendar years within the dataset are : ", calendar_years)

Calendar years within the dataset are :  39


#### part 3
What is the mean and the standard deviation of the per capita daily water consumption?


* Solution : Get the array list of per Capita daily water consumption using slicing and then passing it to Numpy.mean() 
* and Numpy.std() function

In [18]:
capita_daily_water_array = nyc_water[:,3].reshape(1,-1)[0]
print("Mean is : ",np.mean(capita_daily_water_array))
print("Standard deviation is : " ,np.std(capita_daily_water_array))



Mean is :  160.30769230769232
Standard deviation is :  31.51894330370624


##### Part 4
What is the increase or decrease in population from year to year? Use NumPy's `diff` function to create an array
of differences and save that to a variable called "pop_diff", then print that variable to the screen.
* solution: Use np.diff function to return the change Increase and decrease in a list

In [20]:
new_york_city_population_list = nyc_water[:,1].reshape(1,-1)[0]
pop_diff = np.diff(new_york_city_population_list)
print("Increase/decrease in population list is : ",pop_diff)

Increase/decrease in population list is :  [-30461.   17602.   19864.   72119.   53290.   39540.   45192.   23230.
  11243.   -9544.   -8525.   38851.   54443.   77222.   64292.   62582.
  64772.   75631.   84816.   89401.   60618.   16685.5  16685.5  16685.5
  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5 108965.
  77081.   61281.   49530.   44512.   21171.   85025. ]
